name: Release
on:
  workflow_dispatch:
    inputs:
      ci_run_id:
        description: "Run ID of the desired CI run to download artifacts from"
        required: true

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ci.yaml
          workflow_conclusion: success
          run_id: ${{ github.event.inputs.ci_run_id }}
          path: artifacts
          skip_unpack: true

      - name: Exclude test binaries
        run: |
          find artifacts -type f -name magiskboot-\*-wip\*.zip -exec rm -f {} \;

      - name: Extract source package
        run: |
          cd artifacts
          unzip -j srcpkg.zip 'magiskboot_*-src.tar.xz'
          file magiskboot_*-src.tar.xz
          rm -f srcpkg.zip

      - name: Clean up old releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
            keep_latest: 0
            delete_tags: true
            delete_tag_pattern: last-ci
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for 3s
        run: |
          # prevent github to think our release already exists and create us a draft
          sleep 3

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
            name: Last CI build
            target_commitish: dev
            tag_name: last-ci
            body_path: ${{ github.workspace }}/.github/__release_template.txt
            draft: false
            prerelease: false
            fail_on_unmatched_files: true
            files: |
              artifacts/magiskboot_*-src.tar.xz
              artifacts/*.zip
